### ISSUE TITLE
Got a deadlock while syncing data

### ISSUE THREAD

**Issue by Bittu96** [zilliztech/milvus-cdc#103]
Server stopped while the task is running. Can you please help me what might be the issue.

Commeting the log below

**Comment by Bittu96** [comment]
```
[2024/07/30 13:14:52.158 +05:30] [INFO] [writer/channel_writer.go:243] ["receive msg"] [type=LoadCollection] [collection=dfraud_table_cdc_test2] [database=default] [2024/07/30 13:14:52.237 +05:30] [INFO] [writer/channel_writer.go:253] ["finish to handle msg"] [type=LoadCollection] [collection=dfraud_table_cdc_test2] [database=default] POTENTIAL DEADLOCK: Previous place where the lock was grabbed goroutine 11824 lock 0xc0008a2090 ../core/reader/replicate_channel_manager.go:538 reader.(*replicateChannelManager).startReadChannel { r.channelLock.Lock() } <<<<< ../core/reader/replicate_channel_manager.go:537 reader.(*replicateChannelManager).startReadChannel { func (r *replicateChannelManager) startReadChannel(sourceInfo *model.SourceCollectionInfo, targetInfo *model.TargetCollectionInfo) (*replicateChannelHandler, error) { } ../core/reader/replicate_channel_manager.go:306 reader.(*replicateChannelManager).StartReadCollection.func6 { }) } ../core/reader/replicate_channel_manager.go:354 reader.ForeachChannel { for i, source := range sources { } ../core/reader/replicate_channel_manager.go:286 reader.(*replicateChannelManager).StartReadCollection { var channelHandlers []*replicateChannelHandler } ../core/reader/collection_reader.go:126 reader.(*CollectionReader).StartRead.func1.1 { } } ../core/reader/etcd_op.go:276 reader.(*EtcdOp).WatchCollection.func1.1.2.2 { notConsumed := e.subscribeCollectionEvent.Range(func(key string, value api.CollectionEventConsumer) bool { } ../core/util/atomic.go:101 util.(*Map[...]).Range.func1 { m.m.Range(func(key, value any) bool { } /usr/local/Cellar/go/1.22.5/libexec/src/sync/map.go:476 sync.(*Map).Range { } } ../core/util/atomic.go:107 util.(*Map[...]).Range { }) } ../core/reader/etcd_op.go:275 reader.(*EtcdOp).WatchCollection.func1.1.2 { } } ~/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/util/conc/pool.go:81 conc.(*Pool[...]).Submit.func1 { res, err := method() } ~/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67 v2.(*goWorker).run.func1 { f() } Have been trying to lock it again for more than 30s goroutine 11827 lock 0xc0008a2090 ../core/reader/replicate_channel_manager.go:383 reader.(*replicateChannelManager).AddPartition.func1 { r.channelLock.RLock() } <<<<< ../core/reader/replicate_channel_manager.go:382 reader.(*replicateChannelManager).AddPartition.func1 { } } ~/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/util/retry/retry.go:43 retry.Do { for i := uint(0); i < c.attempts; i++ { } ../core/reader/replicate_channel_manager.go:397 reader.(*replicateChannelManager).AddPartition { }, r.retryOptions...) } ../core/reader/collection_reader.go:176 reader.(*CollectionReader).StartRead.func1.2 { err := reader.channelManager.AddPartition(ctx, tmpCollectionInfo, info) } ../core/reader/etcd_op.go:403 reader.(*EtcdOp).WatchPartition.func1.1.2.1 { hasConsume := e.subscribePartitionEvent.Range(func(key string, value api.PartitionEventConsumer) bool { } ../core/util/atomic.go:101 util.(*Map[...]).Range.func1 { m.m.Range(func(key, value any) bool { } /usr/local/Cellar/go/1.22.5/libexec/src/sync/map.go:476 sync.(*Map).Range { } } ../core/util/atomic.go:107 util.(*Map[...]).Range { }) } ../core/reader/etcd_op.go:402 reader.(*EtcdOp).WatchPartition.func1.1.2 { _ = e.handlerWatchEventPool.Submit(func() (struct{}, error) { } ~/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/util/conc/pool.go:81 conc.(*Pool[...]).Submit.func1 { res, err := method() } ~/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67 v2.(*goWorker).run.func1 { f() } Here is what goroutine 11824 doing now goroutine 11824 [chan receive]: github.com/apache/pulsar-client-go/pulsar.(*partitionConsumer).Seek(0xc0006a4380, {{0x1cee, 0x29, 0x0, 0x0}, 0x0, {0x0, 0x0}, {0xc1a2445cdfb7b488, 0x3375687d6d, ...}}) 	/Users/mrudulkatla/go/pkg/mod/github.com/milvus-io/pulsar-client-go@v0.6.10/pulsar/consumer_partition.go:511 +0x227 github.com/apache/pulsar-client-go/pulsar.(*consumer).Seek(0xc0005cef00, {0x106acb080?, 0xc001fc6048?}) 	/Users/mrudulkatla/go/pkg/mod/github.com/milvus-io/pulsar-client-go@v0.6.10/pulsar/consumer_impl.go:594 +0x219 github.com/milvus-io/milvus/pkg/mq/msgstream/mqwrapper/pulsar.(*Consumer).Seek(0xc0006985a0, {0x106ac9248?, 0xc000b36390?}, 0x0) 	/Users/mrudulkatla/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:103 +0x46 github.com/milvus-io/milvus/pkg/mq/msgstream.(*mqMsgStream).Seek(0xc0008b2380, {0x106ac8378, 0x1076156a0}, {0xc00007af00, 0x1, 0x2?}, 0x0) 	/Users/mrudulkatla/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/mq/msgstream/mq_msgstream.go:498 +0x5cd github.com/zilliztech/milvus-cdc/core/reader.getStream({0x106ac8378, 0x1076156a0}, {0x106abec80?, 0xc000a02510?}, {0xc0030874a0, 0x2b}, 0xc003092d20) 	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/stream_creator.go:96 +0x5dd github.com/zilliztech/milvus-cdc/core/reader.(*DisptachClientStreamCreator).CheckConnection(0x10?, {0xc0030874a0?, 0xc000792ab8?}, 0x1051e0ca5?) 	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/stream_creator.go:144 +0x3c github.com/zilliztech/milvus-cdc/core/reader.initReplicateChannelHandler({0x106ac8520, 0xc000a08c80}, 0xc01406c480, 0xc0030fa000, {0x106abed10, 0xc0006ba9a0}, {0x106ad5b40, 0xc0008ff340}, 0xc0008d0660, 0xc000792f20, ...) 	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/replicate_channel_manager.go:1574 +0x91 github.com/zilliztech/milvus-cdc/core/reader.(*replicateChannelManager).startReadChannel(0xc0008a2000, 0xc01406c480, 0xc0030fa000) 	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/replicate_channel_manager.go:552 +0x7c6 github.com/zilliztech/milvus-cdc/core/reader.(*replicateChannelManager).StartReadCollection.func6({0xc0030874a0, 0x2b}, {0xc003000000, 0x2b}) 	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/replicate_channel_manager.go:290 +0x365 github.com/zilliztech/milvus-cdc/core/reader.ForeachChannel({0xc0030b4160, 0x1, 0x641b25d7a0cd6e7?}, {0xc0030b40c0, 0x1, 0x0?}, 0xc000793678) 	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/replicate_channel_manager.go:355 +0x150 github.com/zilliztech/milvus-cdc/core/reader.(*replicateChannelManager).StartReadCollection(0xc0008a2000, {0x106ac8520, 0xc000782460}, 0xc001fd5e60, {0xc000989ce0, 0x1, 0x1}) 	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/replicate_channel_manager.go:287 +0x111c github.com/zilliztech/milvus-cdc/core/reader.(*CollectionReader).StartRead.func1.1(0xc001fd5e60) 	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/collection_reader.go:127 +0x579 github.com/zilliztech/milvus-cdc/core/reader.(*EtcdOp).WatchCollection.func1.1.2.2({0xc000110ae0, 0x20}, 0xc000793c00?) 	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/etcd_op.go:277 +0x4b github.com/zilliztech/milvus-cdc/core/util.(*Map[...]).Range.func1({0x106880600?, 0xc000879ee0?}) 	/Users/mrudulkatla/go/src/milvus-cdc/core/util/atomic.go:102 +0x5e sync.(*Map).Range(0xc0008ff430?, 0xc000793c88) 	/usr/local/Cellar/go/1.22.5/libexec/src/sync/map.go:477 +0x1f8 github.com/zilliztech/milvus-cdc/core/util.(*Map[...]).Range(0x106813b20?, 0xc003082c90?) 	/Users/mrudulkatla/go/src/milvus-cdc/core/util/atomic.go:101 +0x4b github.com/zilliztech/milvus-cdc/core/reader.(*EtcdOp).WatchCollection.func1.1.2() 	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/etcd_op.go:276 +0x4e9 github.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1() 	/Users/mrudulkatla/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/util/conc/pool.go:81 +0xb3 github.com/panjf2000/ants/v2.(*goWorker).run.func1() 	/Users/mrudulkatla/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67 +0x8d created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 356 	/Users/mrudulkatla/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:48 +0x5c make[1]: *** [run] Error 2 make: *** [run] Error 2 
```

**Comment by Bittu96** [comment]
![cdc.log.txt](https://github.com/user-attachments/files/16424431/cdc.log.txt)

**Comment by Bittu96** [comment]
[2024/07/30 13:14:52.158 +05:30] [INFO] [writer/channel_writer.go:243] ["receive msg"] [type=LoadCollection] [collection=dfraud_table_cdc_test2] [database=default]
[2024/07/30 13:14:52.237 +05:30] [INFO] [writer/channel_writer.go:253] ["finish to handle msg"] [type=LoadCollection] [collection=dfraud_table_cdc_test2] [database=default]
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 11824 lock 0xc0008a2090
../core/reader/replicate_channel_manager.go:538 reader.(*replicateChannelManager).startReadChannel { r.channelLock.Lock() } <<<<<
../core/reader/replicate_channel_manager.go:537 reader.(*replicateChannelManager).startReadChannel { func (r *replicateChannelManager) startReadChannel(sourceInfo *model.SourceCollectionInfo, targetInfo *model.TargetCollectionInfo) (*replicateChannelHandler, error) { }
../core/reader/replicate_channel_manager.go:306 reader.(*replicateChannelManager).StartReadCollection.func6 { }) }
../core/reader/replicate_channel_manager.go:354 reader.ForeachChannel { for i, source := range sources { }
../core/reader/replicate_channel_manager.go:286 reader.(*replicateChannelManager).StartReadCollection { var channelHandlers []*replicateChannelHandler }
../core/reader/collection_reader.go:126 reader.(*CollectionReader).StartRead.func1.1 { } }
../core/reader/etcd_op.go:276 reader.(*EtcdOp).WatchCollection.func1.1.2.2 { notConsumed := e.subscribeCollectionEvent.Range(func(key string, value api.CollectionEventConsumer) bool { }
../core/util/atomic.go:101 util.(*Map[...]).Range.func1 { m.m.Range(func(key, value any) bool { }
/usr/local/Cellar/go/1.22.5/libexec/src/sync/map.go:476 sync.(*Map).Range { } }
../core/util/atomic.go:107 util.(*Map[...]).Range { }) }
../core/reader/etcd_op.go:275 reader.(*EtcdOp).WatchCollection.func1.1.2 { } }
~/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/util/conc/pool.go:81 conc.(*Pool[...]).Submit.func1 { res, err := method() }
~/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67 v2.(*goWorker).run.func1 { f() }

Have been trying to lock it again for more than 30s
goroutine 11827 lock 0xc0008a2090
../core/reader/replicate_channel_manager.go:383 reader.(*replicateChannelManager).AddPartition.func1 { r.channelLock.RLock() } <<<<<
../core/reader/replicate_channel_manager.go:382 reader.(*replicateChannelManager).AddPartition.func1 { } }
~/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/util/retry/retry.go:43 retry.Do { for i := uint(0); i < c.attempts; i++ { }
../core/reader/replicate_channel_manager.go:397 reader.(*replicateChannelManager).AddPartition { }, r.retryOptions...) }
../core/reader/collection_reader.go:176 reader.(*CollectionReader).StartRead.func1.2 { err := reader.channelManager.AddPartition(ctx, tmpCollectionInfo, info) }
../core/reader/etcd_op.go:403 reader.(*EtcdOp).WatchPartition.func1.1.2.1 { hasConsume := e.subscribePartitionEvent.Range(func(key string, value api.PartitionEventConsumer) bool { }
../core/util/atomic.go:101 util.(*Map[...]).Range.func1 { m.m.Range(func(key, value any) bool { }
/usr/local/Cellar/go/1.22.5/libexec/src/sync/map.go:476 sync.(*Map).Range { } }
../core/util/atomic.go:107 util.(*Map[...]).Range { }) }
../core/reader/etcd_op.go:402 reader.(*EtcdOp).WatchPartition.func1.1.2 { _ = e.handlerWatchEventPool.Submit(func() (struct{}, error) { }
~/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/util/conc/pool.go:81 conc.(*Pool[...]).Submit.func1 { res, err := method() }
~/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67 v2.(*goWorker).run.func1 { f() }

Here is what goroutine 11824 doing now
goroutine 11824 [chan receive]:
github.com/apache/pulsar-client-go/pulsar.(*partitionConsumer).Seek(0xc0006a4380, {{0x1cee, 0x29, 0x0, 0x0}, 0x0, {0x0, 0x0}, {0xc1a2445cdfb7b488, 0x3375687d6d, ...}})
	/Users/mrudulkatla/go/pkg/mod/github.com/milvus-io/pulsar-client-go@v0.6.10/pulsar/consumer_partition.go:511 +0x227
github.com/apache/pulsar-client-go/pulsar.(*consumer).Seek(0xc0005cef00, {0x106acb080?, 0xc001fc6048?})
	/Users/mrudulkatla/go/pkg/mod/github.com/milvus-io/pulsar-client-go@v0.6.10/pulsar/consumer_impl.go:594 +0x219
github.com/milvus-io/milvus/pkg/mq/msgstream/mqwrapper/pulsar.(*Consumer).Seek(0xc0006985a0, {0x106ac9248?, 0xc000b36390?}, 0x0)
	/Users/mrudulkatla/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go:103 +0x46
github.com/milvus-io/milvus/pkg/mq/msgstream.(*mqMsgStream).Seek(0xc0008b2380, {0x106ac8378, 0x1076156a0}, {0xc00007af00, 0x1, 0x2?}, 0x0)
	/Users/mrudulkatla/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/mq/msgstream/mq_msgstream.go:498 +0x5cd
github.com/zilliztech/milvus-cdc/core/reader.getStream({0x106ac8378, 0x1076156a0}, {0x106abec80?, 0xc000a02510?}, {0xc0030874a0, 0x2b}, 0xc003092d20)
	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/stream_creator.go:96 +0x5dd
github.com/zilliztech/milvus-cdc/core/reader.(*DisptachClientStreamCreator).CheckConnection(0x10?, {0xc0030874a0?, 0xc000792ab8?}, 0x1051e0ca5?)
	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/stream_creator.go:144 +0x3c
github.com/zilliztech/milvus-cdc/core/reader.initReplicateChannelHandler({0x106ac8520, 0xc000a08c80}, 0xc01406c480, 0xc0030fa000, {0x106abed10, 0xc0006ba9a0}, {0x106ad5b40, 0xc0008ff340}, 0xc0008d0660, 0xc000792f20, ...)
	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/replicate_channel_manager.go:1574 +0x91
github.com/zilliztech/milvus-cdc/core/reader.(*replicateChannelManager).startReadChannel(0xc0008a2000, 0xc01406c480, 0xc0030fa000)
	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/replicate_channel_manager.go:552 +0x7c6
github.com/zilliztech/milvus-cdc/core/reader.(*replicateChannelManager).StartReadCollection.func6({0xc0030874a0, 0x2b}, {0xc003000000, 0x2b})
	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/replicate_channel_manager.go:290 +0x365
github.com/zilliztech/milvus-cdc/core/reader.ForeachChannel({0xc0030b4160, 0x1, 0x641b25d7a0cd6e7?}, {0xc0030b40c0, 0x1, 0x0?}, 0xc000793678)
	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/replicate_channel_manager.go:355 +0x150
github.com/zilliztech/milvus-cdc/core/reader.(*replicateChannelManager).StartReadCollection(0xc0008a2000, {0x106ac8520, 0xc000782460}, 0xc001fd5e60, {0xc000989ce0, 0x1, 0x1})
	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/replicate_channel_manager.go:287 +0x111c
github.com/zilliztech/milvus-cdc/core/reader.(*CollectionReader).StartRead.func1.1(0xc001fd5e60)
	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/collection_reader.go:127 +0x579
github.com/zilliztech/milvus-cdc/core/reader.(*EtcdOp).WatchCollection.func1.1.2.2({0xc000110ae0, 0x20}, 0xc000793c00?)
	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/etcd_op.go:277 +0x4b
github.com/zilliztech/milvus-cdc/core/util.(*Map[...]).Range.func1({0x106880600?, 0xc000879ee0?})
	/Users/mrudulkatla/go/src/milvus-cdc/core/util/atomic.go:102 +0x5e
sync.(*Map).Range(0xc0008ff430?, 0xc000793c88)
	/usr/local/Cellar/go/1.22.5/libexec/src/sync/map.go:477 +0x1f8
github.com/zilliztech/milvus-cdc/core/util.(*Map[...]).Range(0x106813b20?, 0xc003082c90?)
	/Users/mrudulkatla/go/src/milvus-cdc/core/util/atomic.go:101 +0x4b
github.com/zilliztech/milvus-cdc/core/reader.(*EtcdOp).WatchCollection.func1.1.2()
	/Users/mrudulkatla/go/src/milvus-cdc/core/reader/etcd_op.go:276 +0x4e9
github.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1()
	/Users/mrudulkatla/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/util/conc/pool.go:81 +0xb3
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/Users/mrudulkatla/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67 +0x8d
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 356
	/Users/mrudulkatla/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:48 +0x5c

make[1]: *** [run] Error 2
make: *** [run] Error 2

**Comment by SimFG** [comment]
@Bittu96 which version you are using?

**Comment by SimFG** [comment]
According to the log, it should be that pulsar does not respond to the seek request for a long time, resulting in channelLock not being released. You can check whether pulsar is functioning normally. If it is working normally, start cdc server again and observe it.

**Comment by SimFG** [comment]
Can you give me more context, such as when the task was created and how long it took to run?

**Comment by Bittu96** [comment]
So I first created a task and started inserting data to the source collection. Around 35k data synced properly into . Post that target milvus is crashing.

As milvus pod was restarting, when through the pulsar logs and found that there is a backlog quota exceeded issue.

```goroutine 507 [running]:
panic({0x4d32000, 0xc002615ac0})
    /usr/local/go/src/runtime/panic.go:987 +0x3bb fp=0xc000491e00 sp=0xc000491d40 pc=0x1c2df5b
github.com/milvus-io/milvus/pkg/mq/msgstream.(*mqMsgStream).AsProducer(0xc001352620, {0xc001df3500?, 0x1, 0x0?})
    /go/src/github.com/milvus-io/milvus/pkg/mq/msgstream/mq_msgstream.go:147 +0x219 fp=0xc000491ed8 sp=0xc000491e00 pc=0x3adb1b9
github.com/milvus-io/milvus/internal/proxy.(*ReplicateStreamManager).newMsgStreamResource.func1()
    /go/src/github.com/milvus-io/milvus/internal/proxy/replicate_stream_manager.go:45 +0x322 fp=0xc000492038 sp=0xc000491ed8 pc=0x4677602
github.com/milvus-io/milvus/pkg/util/resource.(*manager).Get(0xc001515320, {0x5577362, 0x14}, {0xc000537188, 0x16}, 0xc00137d500)
    /go/src/github.com/milvus-io/milvus/pkg/util/resource/resource_manager.go:256 +0x2c6 fp=0xc000492130 sp=0xc000492038 pc=0x44e8b46
github.com/milvus-io/milvus/internal/proxy.(*ReplicateStreamManager).GetReplicateMsgStream(0xc00147e540, {0x5b7fcb8?, 0xc000f08180?}, {0xc000537188, 0x16})
    /go/src/github.com/milvus-io/milvus/internal/proxy/replicate_stream_manager.go:58 +0x1c2 fp=0xc000492348 sp=0xc000492130 pc=0x46778e2
github.com/milvus-io/milvus/internal/proxy.(*Proxy).ReplicateMessage(0xc000501d40, {0x5b7fcb8, 0xc000f08180}, 0xc001512900)
    /go/src/github.com/milvus-io/milvus/internal/proxy/impl.go:5970 +0x11ce fp=0xc0004928d8 sp=0xc000492348 pc=0x464a64e
github.com/milvus-io/milvus/internal/distributed/proxy.(*Server).ReplicateMessage(0x1c39a91?, {0x5b7fcb8?, 0xc000f08180?}, 0xc0015b2e28?)
    /go/src/github.com/milvus-io/milvus/internal/distributed/proxy/service.go:1215 +0x2f fp=0xc000492908 sp=0xc0004928d8 pc=0x4790e0f
github.com/milvus-io/milvus-proto/go-api/v2/milvuspb._MilvusService_ReplicateMessage_Handler.func1({0x5b7fcb8, 0xc000f08180}, {0x533a340?, 0xc001512900})
    /go/pkg/mod/github.com/milvus-io/milvus-proto/go-api/v2@v2.4.5/milvuspb/milvus.pb.go:13850 +0x7b fp=0xc000492948 sp=0xc000492908 pc=0x28dc83b
github.com/milvus-io/milvus/internal/proxy/connection.KeepActiveInterceptor({0x5b7fcb8?, 0xc000f08180}, {0x533a340, 0xc001512900}, 0xc0012fea58?, 0xc0015b2dc8)
    /go/src/github.com/milvus-io/milvus/internal/proxy/connection/util.go:60 +0xa6 fp=0xc000492980 sp=0xc000492948 pc=0x4493fe6
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnar… [message truncated due to size]```

**Comment by SimFG** [comment]
I suspect that the pulsar point has been invalid, causing the cdc to be unable to recover from the interrupted position.

**Comment by Bittu96** [comment]
Hi @SimFG 

How should I proceed to fix this issue?

Also memory usage of target milvus data node is continuously at it's peak even after stopping cdc server. Is there any way to reset pulsar service?

**Comment by SimFG** [comment]
@Bittu96 You need to give the pulsar service more resources, such as increasing the pulsar backlog quota.

**Comment by SimFG** [comment]
@Bittu96 i will close the issue. if you meet other problem when using the cdc, please feel free to open a new issue.
