### ISSUE TITLE
[Bug]: server error: ConsumerBusy: Exclusive consumer is already connected

### ISSUE THREAD

**Issue by rere950303** [zilliztech/milvus-cdc#152]
### Current Behavior

When creating a CDC task based on a specific collection, the CDC app crashes with the log below. When it restarts, it operates normally.
Could it be a Pulsar-related issue?
```
2024.11.06T18:17:49.513[2024/11/06 18:17:49.513 +09:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=4] [error="server error: ConsumerBusy: Exclusive consumer is already connected"]
2024.11.06T18:18:07.766[2024/11/06 18:18:07.766 +09:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=8] [error="server error: ConsumerBusy: Exclusive consumer is already connected"]
2024.11.06T18:18:27.820[2024/11/06 18:18:27.820 +09:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=12] [error="server error: ConsumerBusy: Exclusive consumer is already connected"]
2024.11.06T18:18:47.873[2024/11/06 18:18:47.873 +09:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=16] [error="server error: ConsumerBusy: Exclusive consumer is already connected"]
2024.11.06T18:19:07.913panic: Failed to create consumer by-dev-rootcoord-dml_0, errors = server error: ConsumerBusy: Exclusive consumer is already connected
2024.11.06T18:19:07.914goroutine 10541 [running]:
2024.11.06T18:19:07.914github.com/milvus-io/milvus/pkg/mq/msgstream.(*MqTtMsgStream).AsConsumer(0xc000cf0410, {0x1d83d00, 0xc000c9f310}, {0xc000cade20?, 0x1, 0x0?}, {0xc00091cc00, 0x39}, 0x0)
2024.11.06T18:19:07.914	/home/runner/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/mq/msgstream/mq_msgstream.go:603 +0x425
2024.11.06T18:19:07.914github.com/milvus-io/milvus/pkg/mq/msgdispatcher.NewDispatcher({0x1d83d00, 0xc000c9f310}, {0x1d79f50, 0xc000137560}, 0x1, {0xc000b403f0, 0x16}, 0x0, {0xc00091cc00, 0x39}, ...)
2024.11.06T18:19:07.914	/home/runner/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/mq/msgdispatcher/dispatcher.go:116 +0xa32
2024.11.06T18:19:07.914github.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*dispatcherManager).Add(0xc000cb62d0, {0x1d83d00, 0xc000c9f310}, {0xc000b403f0, 0x2b}, 0xc000cb62d0?, 0xc000137560?)
2024.11.06T18:19:07.914	/home/runner/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/mq/msgdispatcher/manager.go:92 +0x485
2024.11.06T18:19:07.914github.com/milvus-io/milvus/pkg/mq/msgdispatcher.(*client).Register(0xc000915f00, {0x1d83d00, 0xc000c9f310}, {0xc000b403f0, 0x2b}, 0x4d3b01?, 0xc0009bac20?)
2024.11.06T18:19:07.914	/home/runner/go/pkg/mod/github.com/!sim!f!g/milvus/pkg@v0.0.0-20240727040408-64020f3da23b/mq/msgdispatcher/client.go:78 +0x4d4
2024.11.06T18:19:07.914github.com/zilliztech/milvus-cdc/core/reader.(*DisptachClientStreamCreator).GetStreamChan(0xc0009bd2e0, {0x1d83d00, 0xc000c9f310}, {0xc000b403f0, 0x2b}, 0x0)
2024.11.06T18:19:07.914	/home/runner/work/milvus-cdc/milvus-cdc/core/reader/stream_creator.go:138 +0x334
2024.11.06T18:19:07.914github.com/zilliztech/milvus-cdc/core/reader.(*replicateChannelHandler).AddCollection(0xc00074ac80, 0xc00011f300, 0xc000b10770)
2024.11.06T18:19:07.914	/home/runner/work/milvus-cdc/milvus-cdc/core/reader/replicate_channel_manager.go:763 +0x68
2024.11.06T18:19:07.914created by github.com/zilliztech/milvus-cdc/core/reader.initReplicateChannelHandler in goroutine 10481
2024.11.06T18:19:07.914	/home/runner/work/milvus-cdc/milvus-cdc/core/reader/replicate_channel_manager.go:1612 +0x7fa
```

### Expected Behavior

normal cdc task performance

### Steps To Reproduce

1. create cdc task

### Environment

- milvus: 2.4.15
- pulsar: 3.0.1

**Comment by SimFG** [comment]
@rere950303 can you try to use the latest main branch?

**Comment by rere950303** [comment]
I tried again with the latest release just in case, and since the issue did not recur, I will close it.

**Comment by rere950303** [comment]
@SimFG 
Issue has been reopened as it was reproduced. The reproduction steps are as follows:

1. Create a task
2. Delete the task
3. Create a task again for the same collection

After several retries, the CDC server crashes, and when it restarts, it operates normally.
We suspect that during the task deletion process, the Pulsar consumer's connection is not being properly cleaned up. Pulsar has a subscription type called "Exclusive subscription" where only one consumer can subscribe to one partition. Looking at the commits in the main branch, there don't appear to be any related modifications after version v2.0.0-rc2.
Please check this issue.

**Comment by SimFG** [comment]
@rere950303 thanks a lot, i will checkout it

**Comment by SimFG** [comment]
@rere950303 please help to use the latest main branch to checkout the issue. I have fixed and checkout it.

**Comment by rere950303** [comment]
@SimFG 
When running the `make build` command on an M1 MacBook, instead of creating a bin file under the server directory, it creates it in the `bin/cdc` format, and when copying to a container and executing it, an error occurs saying `./milvus-cdc: cannot execute binary file: Exec format error`

**Comment by SimFG** [comment]
you should make the cdc in the container and execute it.

**Comment by rere950303** [comment]
@SimFG it works well thank you

By the way, what does it mean when a warning log like this is recorded?

```
2024.11.07T19:56:17.978[2024/11/07 19:56:17.978 +09:00] [WARN] [msgdispatcher/dispatcher.go:244] ["lag target notified"] [pchannel=by-dev-replicate-msg] [isMain=true] [error="send target timeout, vchannel=by-dev-replicate-msg_8f4f037db0b84a0c8fd35f895a1e511cv0, timeout=5s"]
```

**Comment by SimFG** [comment]
@rere950303 Does not affect normal work, ignore it. If you meet other issues, please open a new issue.
