### ISSUE TITLE
[Bug]: cdc service panic with error `assignment to entry in nil map` during running

### ISSUE THREAD

**Issue by zhuwenxing** [zilliztech/milvus-cdc#41]
### Current Behavior

```
[2024/01/22 11:16:28.743 +00:00] [INFO] [reader/replicate_channel_manager.go:354] ["start to add partition"] [collection_name=PartitionDropChecker__MqbkEkqW] [partition_name=PartitionDropChecker__ujYlyRug] [num=1]
[2024/01/22 11:16:28.743 +00:00] [WARN] [reader/replicate_channel_manager.go:335] ["the partition is dropped in the source and target"] [partition_name=PartitionDropChecker__Qtofp6la]
[2024/01/22 11:16:28.743 +00:00] [INFO] [reader/replicate_channel_manager.go:354] ["start to add partition"] [collection_name=PartitionDropChecker__MqbkEkqW] [partition_name=PartitionDropChecker__PjI9yQr2] [num=1]
[2024/01/22 11:16:28.743 +00:00] [INFO] [reader/replicate_channel_manager.go:354] ["start to add partition"] [collection_name=PartitionDropChecker__MqbkEkqW] [partition_name=PartitionDropChecker__8ysW0oxl] [num=1]
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/zilliztech/milvus-cdc/core/reader.(*replicateChannelHandler).AddPartitionInfo(0xc000d2e460, 0xc02edc18c0, 0xc019c564b0, 0xc001460af0)
	/app/core/reader/replicate_channel_manager.go:586 +0x43f
github.com/zilliztech/milvus-cdc/core/reader.(*replicateChannelManager).AddPartition(0xc00039a6c0, {0x1c3e710?, 0xc000e1cbc0?}, 0xc02edc18c0, 0xc019c564b0)
	/app/core/reader/replicate_channel_manager.go:381 +0x1065
github.com/zilliztech/milvus-cdc/core/reader.(*CollectionReader).StartRead.func1.4(0xc019c564b0)
	/app/core/reader/collection_reader.go:190 +0x3b6
github.com/zilliztech/milvus-cdc/core/reader.(*EtcdOp).GetAllPartition.func2(0xc019c564b0)
	/app/core/reader/etcd_op.go:574 +0x29
github.com/zilliztech/milvus-cdc/core/reader.(*EtcdOp).internalGetAllPartition(0xc00075c420, {0x1c3e710, 0xc000e1cbc0}, {0xc001372f68, 0x2, 0x0?})
	/app/core/reader/etcd_op.go:546 +0x73b
github.com/zilliztech/milvus-cdc/core/reader.(*EtcdOp).GetAllPartition(0xc00135c378?, {0x1c3e710?, 0xc000e1cbc0?}, 0x1845000?)
	/app/core/reader/etcd_op.go:560 +0x7b
github.com/zilliztech/milvus-cdc/core/reader.(*CollectionReader).StartRead.func1()
	/app/core/reader/collection_reader.go:167 +0x962
sync.(*Once).doSlow(0x5ace11?, 0xc0006573e8?)
	/usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/zilliztech/milvus-cdc/core/reader.(*CollectionReader).StartRead(0xc00073c2e0?, {0x1c3e710?, 0xc000e1cbc0?})
	/app/core/reader/collection_reader.go:90 +0x65
github.com/zilliztech/milvus-cdc/server.(*MetaCDC).startInternal(0xc00073c280, 0xc0001bb5f0, 0x1)
	/app/server/cdc_impl.go:474 +0x12b0
github.com/zilliztech/milvus-cdc/server.(*MetaCDC).ReloadTask(0xc00073c280)
	/app/server/cdc_impl.go:164 +0x8b4
github.com/zilliztech/milvus-cdc/server.(*CDCServer).Run(0xc0006927e0, 0xc00055a000)
	/app/server/server.go:53 +0xf2
main.main()
	/app/server/main/main.go:54 +0x425
```

### Environment

build info `[2024/01/22 11:16:01.395 +00:00] [INFO] [tag/tag.go:36] ["base info"] [BuildTime="Mon Jan 22 07:31:48 UTC 2024"] [GitCommit=1971909] [GoVersion="go version go1.18.10 linux/amd64"]`
based on commit https://github.com/zilliztech/milvus-cdc/commit/1971909f14b6bf89770861cc6439168c20356d88

**Comment by zhuwenxing** [comment]
failed job: 
https://qa-jenkins.milvus.io/blue/organizations/jenkins/milvus_cdc_chaos_test/detail/milvus_cdc_chaos_test/35/pipeline

after killing the CDC pod, it seems like it can not run at a healthy status.
```
milvus-cdc-35-c88d7f8b9-czwp6                                     1/1     Running                  6 (15h ago)      15h
```
the new pod restarted many times, which was caused by panic.

**Comment by zhuwenxing** [comment]
still have other panic errors when using image built by https://github.com/zilliztech/milvus-cdc/commit/296dbac9cf0f20858a3cc6351c474cece1961d53

```
[2024/01/23 09:20:59.998 +00:00] [WARN] [reader/replicate_channel_manager.go:662] ["replicate channel handler closed"]
[2024/01/23 09:20:59.998 +00:00] [INFO] [reader/collection_reader.go:160] ["exist collection"] [name=CreateChecker__MF4RwzIz]
[2024/01/23 09:20:59.995 +00:00] [WARN] [reader/replicate_channel_manager.go:710] ["fail to find the collection info"] [error="attempt #0: not found the collection [447217206063673233]: attempt #1: not found the collection [447217206063673233]: attempt #2: not found the collection [447217206063673233]: attempt #3: not found the collection [447217206063673233]: attempt #4: not found the collection [447217206063673233]: attempt #5: not found the collection [447217206063673233]: attempt #6: not found the collection [447217206063673233]: attempt #7: not found the collection [447217206063673233]: attempt #8: not found the collection [447217206063673233]: attempt #9: not found the collection [447217206063673233]: attempt #10: not found the collection [447217206063673233]: attempt #11: not found the collection [447217206063673233]: attempt #12: not found the collection [447217206063673233]: attempt #13: not found the collection [447217206063673233]: attempt #14: not found the collection [447217206063673233]: attempt #15: not found the collection [447217206063673233]: attempt #16: not found the collection [447217206063673233]: attempt #17: not found the collection [447217206063673233]: attempt #18: not found the collection [447217206063673233]: attempt #19: not found the collection [447217206063673233]: attempt #20: not found the collection [447217206063673233]: attempt #21: not found the collection [447217206063673233]: attempt #22: not found the collection [447217206063673233]: attempt #23: not found the collection [447217206063673233]: attempt #24: not found the collection [447217206063673233]: attempt #25: not found the collection [447217206063673233]: attempt #26: not found the collection [447217206063673233]: attempt #27: not found the collection [447217206063673233]: attempt #28: not found the collection [447217206063673233]: attempt #29: not found the collection [447217206063673233]: context canceled"]
[2024/01/23 09:20:59.998 +00:00] [WARN] [reader/collection_reader.go:162] ["fail to start to replicate the collection data"] [collection="ID:447217206067490265 schema:<name:\"CreateChecker__MF4RwzIz\" fields:<fieldID:100 name:\"int64\" is_primary_key:true data_type:Int64 > fields:<fieldID:101 name:\"float\" data_type:Float > fields:<fieldID:102 name:\"varchar\" data_type:VarChar type_params:<key:\"max_length\" value:\"65535\" > > fields:<fieldID:103 name:\"json_field\" data_type:JSON > fields:<fieldID:104 name:\"float_vector\" data_type:FloatVector type_params:<key:\"dim\" value:\"128\" > > > create_time:447217529500991493 virtual_channel_names:\"cdc-test-upstream-44-rootcoord-dml_9_447217206067490265v0\" physical_channel_names:\"cdc-test-upstream-44-rootcoord-dml_9\" shards_num:1 start_positions:<key:\"cdc-test-upstream-44-rootcoord-dml_9\" data:\"\\240\\020\\000\\000\\000\\000\\000\\000\" > 15:447217206063269727 "] [error="context canceled"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11b671b]

goroutine 119082 [running]:
github.com/zilliztech/milvus-cdc/core/writer.(*MilvusDataHandler).ReplicateMessage(0x2d6d616572747370?, {0x1c3e730?, 0xc002f50600?}, 0xc001588bd0)
	/app/core/writer/milvus_handler.go:281 +0x9b
github.com/zilliztech/milvus-cdc/core/writer.(*replicateMessageHandler).startHandleMessageLoop.func1()
	/app/core/writer/replicate_message_manager.go:74 +0xa5
created by github.com/zilliztech/milvus-cdc/core/writer.(*replicateMessageHandler).startHandleMessageLoop
	/app/core/writer/replicate_message_manager.go:67 +0x56
```
